services:
  postgres:
    image: postgres:latest
    container_name: postgresZlata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: zlatadb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  hotel:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: zlatadb
    depends_on:
      - postgres


volumes:
  postgres_data: