spring:
  application:
    name: Hotel

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/zlatadb
    username: postgresps
    password: 1111

#  spring.application.name=Hotel
