spring:
  application:
    name: Hotel

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ZlataDB
    username: postgres
    password: 1111


#  spring.application.name=Hotel
