spring:
  application:
    name: Hotel

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    placeholders:
      defaultSchema: public

    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          default_schema: public

#  spring.application.name=Hotel


#spring:
#  application:
#    name: Hotel
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/Test
#    username: postgres
#    password: 1111
#
#  jpa:
#    properties:
#      hibernate:
#        default_schema: public
#    hibernate:
#      ddl-auto: validate
#
#  flyway:
#    enabled: true
#    schemas: public
#    default-schema: public

#  spring.application.name=Hotel
